AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/*.rake'
    - 'lib/tasks/rake_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false
  Exclude:
    - 'spec/services/**/*'
    - 'spec/factories/**/*'

Documentation:
  Enabled: false

AsciiComments:
  Enabled: false

Rails:
  Enabled: true
