development:
  adapter: mysql2
  encoding: utf8
  database: h2o_ror_front_end_development
  username: root
  password: root
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: 3300

production:
  adapter: mysql2
  encoding: utf8
  database: h2o_ror_front_end_production
  username: root
  password: root
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: 3300

test:
  adapter: mysql2
  encoding: utf8
  database: h2o_ror_front_end_test
  username: root
  password: root
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: 3300
