development:
  adapter: mysql2
  encoding: utf8
  database: h2o_ror_front_end_development
  username: root
  password:
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: h2o_ror_front_end_test
  username: root
  password:
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: 3306
