development:
  adapter: mysql2
  encoding: utf8
  database: h2o_ror_front_end_development
  username: root
  password: root
  host: localhost
  port: 3300

production:
  adapter: mysql2
  encoding: utf8
  database: ENV['CLEARDB_DATABASE_URL']
  username: 
  password:  
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: ENV['CLEARDB_DATABASE_URL']
  username: root
  password: root
  host: localhost
  port: 3300
